apiVersion: v1
kind: ConfigMap
metadata:
  name: node0-config
  namespace: ograc
data:
  deploy_param.json: |
    {
      "deploy_mode": "file",
      "deploy_user": "ogdba:ogdba",
      "node_id": "0",
      "cms_ip": "192.168.86.1;192.168.86.2",
      "storage_dbstor_fs": "foo",
      "storage_share_fs": "share",
      "storage_archive_fs": "archive",
      "storage_metadata_fs": "metadata",
      "ograc_in_container": "1",
      "share_logic_ip": "10.77.78.1",
      "archive_logic_ip": "10.77.78.2",
      "metadata_logic_ip": "10.77.78.3",
      "storage_logic_ip": "10.77.78.4",
      "db_type": "0",
      "mes_ssl_switch": true,
      "MAX_ARCH_FILES_SIZE": "300G",
      "redo_num": "6",
      "redo_size": "5G"
    }
  mem_spec: "1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node1-config
  namespace: ograc
data:
  deploy_param.json: |
    {
      "deploy_mode": "file",
      "deploy_user": "ogdba:ogdba",
      "node_id": "1",
      "cms_ip": "192.168.86.1;192.168.86.2",
      "storage_dbstor_fs": "foo",
      "storage_share_fs": "share",
      "storage_archive_fs": "archive",
      "storage_metadata_fs": "metadata",
      "ograc_in_container": "1",
      "share_logic_ip": "10.77.78.1",
      "archive_logic_ip": "10.77.78.2",
      "metadata_logic_ip": "10.77.78.3",
      "storage_logic_ip": "10.77.78.4",
      "db_type": "0",
      "mes_ssl_switch": true,
      "MAX_ARCH_FILES_SIZE": "300G",
      "redo_num": "6",
      "redo_size": "5G"
    }
  mem_spec: "1"